// src/pages/Home.tsx
import { Hero } from "../components/Hero";
import { SocialProof } from "../components/SocialProof";
import { Work } from "../components/Work";
import { Philosophy } from "../components/Philosophy";
import { About } from "../components/About";
import { Services } from "../components/Services";
import { FAQ } from "../components/FAQ";
import { FinalCTA } from "../components/FinalCTA";

export function Home() {
  return (
    <>
      <Hero />
      <SocialProof />
      <Work />
      <Philosophy />
      <About />
      <Services />
      <FAQ />
      <FinalCTA />
    </>
  );
}

// src/pages/Home.vue
<script setup lang="ts">
import Hero from "../components/Hero.vue";
import SocialProof from "../components/SocialProof.vue";
import Work from "../components/Work.vue";
import Philosophy from "../components/Philosophy.vue";
import About from "../components/About.vue";
import Services from "../components/Services.vue";
import FAQ from "../components/FAQ.vue";
import FinalCTA from "../components/FinalCTA.vue";
</script>

<template>
  <Hero />
  <SocialProof />
  <Work />
  <Philosophy />
  <About />
  <Services />
  <FAQ />
  <FinalCTA />
</template>
